services:
  # Service Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./api/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - movies-service
      - notifications-service
      - rooms-service
      - search-service
      - sessions-service
      - users-service
    networks:
      - simplo-cine-network

  # Service Frontend (Next.js)
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    networks:
      - simplo-cine-network

  # Service de gestion des films
  movies-service:
    build: ./micro-services/movies-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres_movies
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/movies_db
    networks:
      - simplo-cine-network

  postgres_movies:
    ports:
      - "5432:5432"
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies_db
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data
    networks:
      - simplo-cine-network

  # Service de notifications
  notifications-service:
    build: ./micro-services/notifications-service
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      # Ajoutez ici les variables d'environnement nécessaires sans les secrets pour l'instant
      - REDIS_URL=redis://redis:6379/0
    networks:
      - simplo-cine-network

  # Service de gestion des salles
  rooms-service:
    build: ./micro-services/rooms-service
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      # Ajoutez ici les variables d'environnement nécessaires sans les secrets pour l'instant
      - DATABASE_URL=postgres://user:password@postgres-db:5432/rooms_db
    networks:
      - simplo-cine-network

  # Service de recherche
  search-service:
    build: ./micro-services/search-service
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      # Ajoutez ici les variables d'environnement nécessaires sans les secrets pour l'instant
      - DATABASE_URL=postgres://user:password@postgres-db:5432/search_db
    networks:
      - simplo-cine-network

  # Service de gestion des sessions
  sessions-service:
    build: ./micro-services/sessions-service
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
      # Ajoutez ici les variables d'environnement nécessaires sans les secrets pour l'instant
      - DATABASE_URL=postgres://user:password@postgres-db:5432/sessions_db
    networks:
      - simplo-cine-network

  postgres_sessions:
    ports:
      - "5434:5432"
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sessions_db
    volumes:
      - postgres_data_session:/var/lib/postgresql/data
    networks:
      - simplo-cine-network

  # Service de gestion des utilisateurs
  users-service:
    build: ./micro-services/users-service
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@postgres_users:5432/users_db
    networks:
      - simplo-cine-network

  postgres_users:
    ports:
      - "5433:5432"
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    volumes:
      - postgres_data_user:/var/lib/postgresql/data
    networks:
      - simplo-cine-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - simplo-cine-network

  grafana:
    image: grafana/grafana
    ports:
      - "3010:3000"
    networks:
      - simplo-cine-network

volumes:
  # Réseau personnalisé pour simplo-cine
  postgres_data_movie:
  postgres_data_user:
  postgres_data_session:
networks:
  simplo-cine-network:
    driver: bridge
