version: '3.8'

services:
  # Service Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./api/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - movies-service
      - notifications-service
      - rooms-service
      - search-service
      - sessions-service
      - users-service

  # Service Frontend (Next.js)
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    command: npm run dev

  # Service de gestion des films
  movies-service:
    build: ./micro-services/movies-service
    ports:
      - "3002:3000"

  # Service de notifications
  notifications-service:
    build: ./micro-services/notifications-service
    ports:
      - "3003:3000"

  # Service de gestion des salles
  rooms-service:
    build: ./micro-services/rooms-service
    ports:
      - "3004:3000"

  # Service de recherche
  search-service:
    build: ./micro-services/search-service
    ports:
      - "3005:3000"

  # Service de gestion des sessions
  sessions-service:
    build: ./micro-services/sessions-service
    ports:
      - "3006:3000"

  # Service de gestion des utilisateurs
  users-service:
    build: ./micro-services/users-service
    ports:
      - "3007:3000"
