name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
    paths-ignore:
      - version/*.tar

jobs:
  deploy-on-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 45.81.84.133
          username: "adminlocal"
          password: "cdadevops2024"
          port: 9049
          script: |
            # Arrêter tous les conteneurs s'ils existent
            containers=$(sudo docker ps -q)
            if [ -n "$containers" ]; then
              sudo docker stop $containers
            fi

            # Supprimer tous les conteneurs + network s'ils existent
            containers=$(sudo docker ps -a -q)
            if [ -n "$containers" ]; then
              sudo docker rm $containers
              # Supprime le network custom
              sudo docker network rm simplo-cine_simplo-cine-network || true
            fi

            # Vérifier si le répertoire existe, sinon le cloner
            if [ ! -d ~/devops/simplo-cine ]; then
              mkdir -p ~/devops
              git clone --branch develop https://github.com/Florence-Martin/simplo-cine ~/devops/simplo-cine
            else
              cd ~/devops/simplo-cine
              git pull origin develop
            fi

  build-and-run-on-vps:
    runs-on: ubuntu-latest
    needs: deploy-on-vps

    steps:
      - name: Build Docker Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 45.81.84.133
          username: "adminlocal"
          password: "cdadevops2024"
          port: 9049
          script: |
            cd ~/devops/simplo-cine
            
            # Lire la version depuis le fichier version.txt
            VERSION=$(cat ./version/version.txt)
            
            # Construire et taguer les images Docker
            sudo docker-compose build
            sudo docker tag movies-service movies-service:$VERSION
            sudo docker tag notifications-service notifications-service:$VERSION
            sudo docker tag rooms-service rooms-service:$VERSION
            sudo docker tag search-service search-service:$VERSION
            sudo docker tag sessions-service sessions-service:$VERSION
            sudo docker tag users-service users-service:$VERSION

            # Sauvegarder les images Docker dans le répertoire version/
            mkdir -p ~/devops/simplo-cine/version
            sudo docker save -o ~/devops/simplo-cine/version/movies-service_$VERSION.tar movies-service:$VERSION
            sudo docker save -o ~/devops/simplo-cine/version/notifications-service_$VERSION.tar notifications-service:$VERSION
            sudo docker save -o ~/devops/simplo-cine/version/rooms-service_$VERSION.tar rooms-service:$VERSION
            sudo docker save -o ~/devops/simplo-cine/version/search-service_$VERSION.tar search-service:$VERSION
            sudo docker save -o ~/devops/simplo-cine/version/sessions-service_$VERSION.tar sessions-service:$VERSION
            sudo docker save -o ~/devops/simplo-cine/version/users-service_$VERSION.tar users-service:$VERSION
            sudo docker tag front front:$VERSION
            sudo docker tag nginx nginx:$VERSION
            sudo docker tag prometheus prometheus:$VERSION
            sudo docker tag grafana grafana:$VERSION

            # Copie des fichiers versionnés dans le dépôt
            cp ~/devops/simplo-cine/version/*.tar ~/devops/simplo-cine/version/

            # Engager et pousser les changements vers le dépôt
            git config --global user.email "pro.legrand.thomas@gmail.com"
            git config --global user.name "Legrand Thomas"
            git add version/*.tar
            git commit -m "[skip ci] Ajout des images versionnées pour la version $VERSION"
            git push origin develop

      - name: Start Docker Containers
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 45.81.84.133
          username: "adminlocal"
          password: "cdadevops2024"
          port: 9049
          script: |
            cd ~/devops/simplo-cine
            sudo docker network rm simplo-cine_simplo-cine-network || true
            sudo docker-compose up -d
